language: scala
scala:
  - 2.11.11
  - 2.12.6
jdk:
  - oraclejdk11

matrix:
  include:
    - jdk: oraclejdk8
      dist: trusty
      scala: 2.11.11
    - jdk: oraclejdk8
      dist: trusty
      scala: 2.12.6

script:
  - sbt clean coverage test
